
server:
  server.context-path: /
  port: 8080
  session-timeout: 60
  tomcat.uri-encoding: UTF-8

datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.16.10.210:3306/app_put?useUnicode=true&amp;characterEncoding=utf-8
  username: caipiao
  password: F%46tff%^#@e

spring:
  application:
    name: /
  profiles:
    active: localhost
  redis:
    cluster:
      max-redirects: 3
      nodes: 172.16.10.210:7001,172.16.10.210:7002,172.16.10.210:7003
    jedis:
      pool:
         max-idle: 100
         max-total: 600
         max-wait: 1000ms
    timeout: 3000ms
  cache:
    redis:
      namespace: comment
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
      password: 1234qwer
    elasticsearch:
      cluster-nodes: localhost:9300
#      properties:
#        http.enabled : true
#        host: localhost
#        port: 9300
      repositories:
        enabled: true

# MyBatis
mybatis:
    typeAliasesPackage: com.fly.caipiao.comment
    mapperLocations: classpath*:mapper/**/*.xml
    configuration:
      mapUnderscoreToCamelCase: true

#logger
logging:
  file: logs/message.log
  level:
    root: info
    com.fly.caipiao.comment.service: debug


---
spring:
  profiles: dev
server:
  port: 8080
---
spring:
  profiles: test210
server:
  port: 8091
---
spring:
  profiles: test89
server:
  port: 8091
---
spring:
  profiles: prod
server:
  port: 8091

