server:
  server.context-path: /
  port: 8080
  session-timeout: 60
  tomcat.uri-encoding: UTF-8

datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.20.122:3306/lottery_base?useUnicode=true&amp;characterEncoding=utf-8
    username: cpuser
    password: cppass

spring:
  cache:
    redis:
      namespace: comment
  redis:
    cluster:
        nodes: 172.20.20.120:7000,172.20.20.119:7000,172.20.20.121:7000
        max-redirects: 3
    jedis:
      pool:
        max-idle: 100
        max-total: 600
        max-wait: 1

# MyBatis
mybatis:
    typeAliasesPackage: com.fly.caipiao.comment
    mapperLocations: classpath*:mapper/**/*.xml
    configuration:
      mapUnderscoreToCamelCase: true

#logger
logging:
  file: logs/message.log
  level:
    root: info
    com.fly.caipiao.comment.service: debug


