server:
  server.context-path: /
  port: 8091
  session-timeout: 60
  tomcat.uri-encoding: UTF-8

datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lottery_base?useUnicode=true&amp;characterEncoding=utf-8
    username: caipiao
    password: wgf%^F87qew

spring:
  cache:
    redis:
      namespace: comment
  redis:
    cluster:
        nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
        max-redirects: 3
    jedis:
      pool:
        max-idle: 100
        max-total: 600
        max-wait: 1

# MyBatis
mybatis:
    typeAliasesPackage: com.fly.caipiao.comment
    mapperLocations: classpath*:mapper/**/*.xml
    configuration:
      mapUnderscoreToCamelCase: true

#logger
logging:
  file: logs/message.log
  level:
    root: info
    com.fly.caipiao.comment.service: debug


